var GAME_LEVELS = [
  ["  x           xx!xxxxxx!xxxxxxx!xx                                              ",
   "  x            x!x    x!x     x!x                                               ",
   "  x            x!x    x!x     x!x                                               ",
   "  x     @       v      v       v                                                ",
   "  x    xxx                                                                      ",
   "  x                                                                             ",
   "  x                                                                             ",
   "  x                                                                             ",
   "  x                                                                             ",
   "  x                                                                             ",
   "  x                                                                             ",
   "  x                                        oo                                xxx",
   "  x                                                                          x x",
   "  x                                       xxxx                               x x",
   "  x                                                                          x x",
   "  x                                   xxx      xxx                o o        x x",
   "  x                 o       o                                   xxxxxxx  o   x x",
   "  xxxxxxxxxxxxx    xxx     xxx    xxx!!!!!!xx!!!!!!xxx      xxxxx     xxxxxxxx x",
   "              x                   x!!!!!!!!!!!!!!!!!!x                         x",
   "              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                     x",
   "              x!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!x    o    o #   o     x",
   "              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                             x!x  ",
   "                                                                        xxxxxx                               x!x  ",
   "                                                                       x!!!!!!x                              x!x  ",
   "                                                                      x!!!!!!!!x                             x!x  ",
   "                                                                         vvvv                                x!x  ",
   "                                                                                                 o#         xx!x  ",
   "                                                xxxxx                                         xxxxxxxx   xxxx!!x  ",
   "                                               x!!!!!x                                       #x!!!!!!!   !!!!!!x  ",
   "                                               x!!!!!x                          o       xxxxxxxxxxx!!!   !!!xxxx  ",
   "                                               x!!!!!x                         xxx                 !!!   !!!      ",
   "                                               x!!!!!x                                             !!!   !!!      ",
   "                                               xx|||xx                 o                           !!!   !!!      ",
   "                                                                      xxx                          !!!   !!!      ",
   "                             x                                                                     !!!   !!!      ",
   "                            x                                                                      !!! o !!!      ",
   "      xxxxxx    xxxxxx     x                      o                            o                   !!!   !!!      ",
   "            x  xx!!!!xx   x                                                   xxx                  !!!   !!!      ",
   "        ?   x xx!!!!!!xx x                                                                         !!!   !!!      ",
   "            xxx!!!!!!!!xxxx o                                                                      !!!   !!!      ",
   "            xxxvvvvvvvvxxxxxxx o               x     x                    oo #                     !!! o !!!      ",
   "    @                         xxx              x     x      o           xxxxxx                     !!!   !!!      ",
   " xxxx                                 xx       x     x     xxxx        x      x                    !!!   !!!      ",
   "    x      o                         x         x     x               xx        xx                  !!!   !!!      ",
   "    x      x                      o xx!!!!!!!!xx     xx!!!!!!!!!!!xxxx!!!!!!!!!!xxxx!!!!!!!!!!!!!!!!!x   x!!!!!!!!",
   "    x      x                    xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x   x!!!!!!!!",
   "    x!!!!!!x                  xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x     x!!!!!!!",
   "    x!!!!!!x                xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx       xx!!!!!",
   "    x!!!!!!!     o    o   xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  o   o  x!!!!!",
   "     x!!!x!!!!xxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxx!!!!!",
   "      xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                           xxxxxxxxxxxxxxxx                                   ",
   "                                                           xxx!!!!!!!!!!xxx                                   ",
   "                                                            xx!!!!!!!!!!xx                                    ",
   "                                                              x!!!!!!!!!x                                     ",
   "                                                               x!!!!!!x                                       ",
   "                                                                 vvvv                                         ",
   "                                                                                                              ",
   "                                                          x                                                   ",
   "                                                           x            x                                     ",
   "                                                            x           x                                     ",
   "                                                             x          x            x                        ",
   "                                                             x          xxxxxxxxxxxxxx                        ",
   "                                                                        x!!!!!!!!!!!!x                        ",
   "                                                                        xxxxx||||xxxxx                        ",
   "                                                             xxx  oo  xxx            x                        ",
   "                                                            xx                       x                        ",
   "                                                      xxxxxxxx                       x                        ",
   "                                                   xxxx                              x                        ",
   "                                                      x===                           x                        ",
   "                                            xxx       x===                           x                        ",
   "                                                      x                                                       ",
   "                                                      x                                                       ",
   "                                                    xxx                      oo                               ",
   "                                                      x                     xxxxx                             ",
   "                                           xxx        x  oo xxx  #           xxx                              ",
   "                                                      xxxxxxxxxxxxxxxx                  oo                    ",
   "                                                 o o  x!!!!!!!!!!!!!!x                 xxxxx                  ",
   "                                                  #   x!!!!!!!!!!!!!!x                  xxx                   ",
   "                                              xxxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                                          xxxx                                    oo                          ",
   "  xxx                                     x                                      xxxxx                   xxx  ",
   "  x x                                 xxxxx                               o o     xxx                    x x  ",
   "  x                                       x                              xxxxx                             x  ",
   "  x                                       x                              x   x                             x  ",
   "  x                               xxxx    x                         x    x x x    xxxxx                    x  ",
   "  x                                       x                         xxxxxx xxx    x!!!x                    x  ",
   "  x                           ?    o o    x                              xx        vvv                     x  ",
   "  x                           xx          x                                                       oo       x  ",
   "  x                           x    xxx    x       x    x    x    x                               xxx       x  ",
   "  x      @                    xxxxxxxxxxxxx  x oo x||||x oo x||||x oo xx    xx                 xxxxx       x  ",
   "  x     xx      ooooo  #      x           xxxx    x!!!!x    x!!!!x    x!!!!!!x    ooooo  #                 x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                   ",
   "     x                                             x      x                                                   ",
   "     x          x x xxx x x       x     x x xx  x  x      x                                                   ",
   "     x           x  x x x x        x x x  x x x x         x                                                   ",
   "     x           x  xxx xxx         x x   x x  xx  x      x                                                   ",
   "     x   @                                                x                                                   ",
   "     x                                                    x                                                   ",
   "     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                   ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
